import * as constants from './constants';

export const getInitInfo = () => (
  {
    type: constants.GET_INIT_INFO,
  }
);

export const insertAppInfo = (
  CLIENT_TYPE,
  LANG_LIST,
  NAME_KOR,
  APP_ABBR_KOR,
  DSCR_KOR,
  NAME_ENG,
  APP_ABBR_ENG,
  DSCR_ENG,
  NAME_CHN,
  APP_ABBR_CHN,
  DSCR_CHN,
  CATG_ID,
  SRC_PATH,
  history,
  UploadFilesIcon,
  VER_1,
  VER_2,
  VER_3,
  Workstep,
  WORK_STEP_URL,
  UploadFilesWork,
  AppManual,
  APP_MANUAL_URL,
  UploadFilesManual,
  UploadFilesScreenshot,
  KEYWORD,
  INTL_YN,
  linkType,
  LINK_URL,
  // WIDTH,
  // HEIGHT,
  LINK_METHOD,
  LINK_PARAM,
  SEC_REQ_YN,
  appList1,
  appList2,
  // DFLT_SKIN,
  SERVICE_FORM,
  ITEM_VALUE,
) => ({
  type: constants.INSERT_APP_INFO,
  payload: {
    CLIENT_TYPE,
    LANG_LIST,
    NAME_KOR,
    APP_ABBR_KOR,
    DSCR_KOR,
    NAME_ENG,
    APP_ABBR_ENG,
    DSCR_ENG,
    NAME_CHN,
    APP_ABBR_CHN,
    DSCR_CHN,
    CATG_ID,
    SRC_PATH,
    history,
    UploadFilesIcon,
    VER_1,
    VER_2,
    VER_3,
    Workstep,
    WORK_STEP_URL,
    UploadFilesWork,
    AppManual,
    APP_MANUAL_URL,
    UploadFilesManual,
    UploadFilesScreenshot,
    KEYWORD,
    INTL_YN,
    linkType,
    LINK_URL,
    // WIDTH,
    // HEIGHT,
    LINK_METHOD,
    LINK_PARAM,
    SEC_REQ_YN,
    appList1,
    appList2,
    // DFLT_SKIN,
    SERVICE_FORM,
    ITEM_VALUE,
  },
});
