export const LOADING_TECHSAFE_DETAIL_SEARCH_SAGA = 'apps/hyPm/InformNote/note/LOADING_TECHSAFE_DETAIL_SEARCH_SAGA';
export const LOADING_TECHSAFE_DETAIL_SEARCH = 'apps/hyPm/InformNote/note/LOADING_TECHSAFE_DETAIL_SEARCH';
