
export const USER_SEARCH_SAGA = 'USER_SEARCH_SAGA';
export const USER_SEARCH_HISTORY_SAGA = 'USER_SEARCH_HISTORY_SAGA';
export const USER_HISTORY_DELETE_SAGA = 'USER_HISTORY_DELETE_SAGA';
export const USER_HISTORY_DELETEALL_SAGA = 'USER_HISTORY_DELETEALL_SAGA';
export const USER_HISTORY_INSERT_SAGA = 'USER_HISTORY_INSERT_SAGA';

export const USER_PROFILE = 'USER_PROFILE';
export const USER_ENABLE_SEARCH_RESULT_VIEW = 'USER_ENABLE_SEARCH_RESULT_VIEW';
export const USER_CLEAR_SEARCH_RESULT_VIEW = 'USER_CLEAR_SEARCH_RESULT_VIEW';
export const USER_DISABLE_SEARCH_RESULT_VIEW = 'USER_DISABLE_SEARCH_RESULT_VIEW';
export const USER_SUCCESS_GET_RESULT = 'USER_SUCCESS_GET_RESULT';
export const USER_HISTORY_SUCCESS_GET_RESULT = 'USER_HISTORY_SUCCESS_GET_RESULT';
export const USER_HISTORY_FAIL_GET_RESULT = 'USER_HISTORY_FAIL_GET_RESULT';
export const USER_HISTORY_DELETE_SUCCESS = 'USER_HISTORY_DELETE_SUCCESS';
export const USER_HISTORY_DELETEALL_SUCCESS = 'USER_HISTORY_DELETEALL_SUCCESS';
export const USER_HISTORY_INSERT_SUCCESS = 'USER_HISTORY_INSERT_SUCCESS';
export const USER_HISTORY_INSERT_FAIL = 'USER_HISTORY_INSERT_FAIL';
export const USER_PROFILE_DATA_SAGA = 'USER_PROFILE_DATA_SAGA';
export const USER_HISTORY_UPDATE_SUCCESS = 'USER_HISTORY_UPDATE_SUCCESS';
