const prefix = '/apps/StyleDesigner';

export const GET_METADATA_SAGA = `${prefix}/GET_METADATA_SAGA`;
export const SET_INIT_DATA_REDUCER = `${prefix}/SET_INIT_DATA_REDUCER`;
export const SET_VIEW_DATA_REDUCER = `${prefix}/SET_VIEW_DATA_REDUCER`;
export const SET_COMP_DATA_REDUCER = `${prefix}/SET_COMP_DATA_REDUCER`;
export const SET_WORK_INFO_REDUCER = `${prefix}/SET_WORK_INFO_REDUCER`;
export const SET_TOP_MENUS_REDUCER = `${prefix}/SET_TOP_MENUS_REDUCER`;
export const SET_VIEW_DATA_COMP_ITEM_REDUCER = `${prefix}/SET_VIEW_DATA_COMP_ITEM_REDUCER`;
export const SET_INIT_LIST_DATA_REDUCER = `${prefix}/SET_INIT_LIST_DATA_REDUCER`;
export const SET_COMPONENT_POOL_REDUCER = `${prefix}/SET_COMPONENT_POOL_REDUCER`;
export const SET_SYSMETA_LIST_REDUCER = `${prefix}/SET_SYSMETA_LIST_REDUCER`;
export const SET_SYS_COMP_ITEM_REDUCER = `${prefix}/SET_SYS_COMP_ITEM_REDUCER`;
export const ENABLE_CONTENT_LOADING = `${prefix}/ENABLE_CONTENT_LOADING`;
export const DISABLE_CONTENT_LOADING = `${prefix}/DISABLE_CONTENT_LOADING`;
export const ON_CHANGE_WIDTHS = `${prefix}/ON_CHANGE_WIDTHS`;
export const ON_CHANGE_HEIGHTS = `${prefix}/ON_CHANGE_HEIGHTS`;
export const UPDATE_CELL_STYLE = `${prefix}/UPDATE_CELL_STYLE`;
export const ADD_METADATA_SAGA = `${prefix}/ADD_METADATA_SAGA`;
