export const INIT_MANUALMANGERBYREDUCR = 'apps/ManualManager/ManualMaster/INIT_MANUALMANGERBYREDUCR';
export const SET_MOVEPAGETYPEBYREDUCR = 'apps/ManualManager/ManualMaster/SET_MOVEPAGETYPEBYREDUCR';

export const INIT_DEFAULTMGR_REDUCR = 'apps/ManualManager/ManualMaster/INIT_DEFAULTMGR_REDUCR';
export const SET_DEFAULTMGRCHANGEVALUE_REDUCR = 'apps/ManualManager/ManualMaster/SET_DEFAULTMGRCHANGEVALUE_REDUCR';
export const SET_DEFAULTMGR_REDUCR = 'apps/ManualManager/ManualMaster/SET_DEFAULTMGR_REDUCR';
export const GET_DEFAULTMGR_SAGA = 'apps/ManualManager/ManualMaster/GET_DEFAULTMGR_SAGA';
export const ADD_DEFAULTMGR_SAGA = 'apps/ManualManager/ManualMaster/ADD_DEFAULTMGR_SAGA';
export const MODIFY_DEFUALTMGR_SAGA = 'apps/ManualManager/ManualMaster/MODIFY_DEFUALTMGR_SAGA';
export const ADD_TAB_INFO_REDUCR = 'apps/ManualManager/ManualMaster/ADD_TAB_INFO_REDUCR';
export const SET_TAB_IDX_REDUCR = 'apps/ManualManager/ManualMaster/SET_TAB_IDX_REDUCR';
export const REMOVE_TAB_INFO_REDUCR = 'apps/ManualManager/ManualMaster/REMOVE_TAB_INFO_REDUCR';
export const GET_EDITOR_INFO_SAGA = 'apps/ManualManager/ManualMaster/GET_EDITOR_INFO_SAGA';
export const SET_EDITORMGR_REDUCR = 'apps/ManualManager/ManualMaster/SET_EDITORMGR_REDUCR';
export const SET_IS_EDITORMGR_REDUCR = 'apps/ManualManager/ManualMaster/SET_IS_EDITORMGR_REDUCR';
export const SET_PAGE_TYPE_REDUCR = 'apps/ManualManager/ManualMaster/SET_PAGE_TYPE_REDUCR';
export const SAVE_EDITOR_SAGA = 'apps/ManualManager/ManualMaster/SAVE_EDITOR_SAGA';
export const SET_TAB_NAME_REDUCR = 'apps/ManualManager/ManualMaster/SET_TAB_NAME_REDUCR';
export const RESET_EDITORMGR_REDUCR = 'apps/ManualManager/ManualMaster/RESET_EDITORMGR_REDUCR';
export const MOVE_TAB_COMPONENT_REDUCR = 'apps/ManualManager/ManualMaster/MOVE_TAB_COMPONENT_REDUCR';
export const ADD_EDITOR_COMPONENT_REDUCR = 'apps/ManualManager/ManualMaster/ADD_EDITOR_COMPONENT_REDUCR';
export const SET_ADD_EDITOR_COMPONENT_ID_REDUCR = 'apps/ManualManager/ManualMaster/SET_ADD_EDITOR_COMPONENT_ID_REDUCR';
export const SET_FOCUS_EDITOR_COMPONENT_IDX_REDUCR = 'apps/ManualManager/ManualMaster/SET_FOCUS_EDITOR_COMPONENT_IDX_REDUCR';
export const SET_EDITOR_COMPONENT_VALUE_REDUCR = 'apps/ManualManager/ManualMaster/SET_EDITOR_COMPONENT_VALUE_REDUCR';
export const SET_EDITOR_COMPONENT_INDEX_REDUCR = 'apps/ManualManager/ManualMaster/SET_EDITOR_COMPONENT_INDEX_REDUCR';
export const REMOVE_EDITOR_COMPONENT_REDUCR = 'apps/ManualManager/ManualMaster/REMOVE_EDITOR_COMPONENT_REDUCR';
export const SET_ADD_EDITOR_COMPONENT_IDX_REDUCR = 'apps/ManualManager/ManualMaster/SET_ADD_EDITOR_COMPONENT_IDX_REDUCR';
export const SET_EDITOR_COMPONENT_LIST_REDUCR = 'apps/ManualManager/ManualMaster/SET_EDITOR_COMPONENT_LIST_REDUCR';
export const REVISION_MANUAL_SAGA = 'apps/ManualManager/ManualMaster/REVISION_MANUAL_SAGA';
export const CONFIRM_DEFAULT_MGR_SAGA = 'apps/ManualManager/ManualMaster/CONFIRM_DEFAULT_MGR_SAGA';
export const RESET_DEFAULT_MGR_SAGA = 'apps/ManualManager/ManualMaster/RESET_DEFAULT_MGR_SAGA';
export const REMOVE_MANUAL_SAGA = 'apps/ManualManager/ManualMaster/REMOVE_MANUAL_SAGA';
export const GET_DEFAULTMGR_BY_VERSION_SAGA = 'apps/ManualManager/ManualMaster/GET_DEFAULTMGR_BY_VERSION_SAGA';

// :::::::::::::::::::::::: 사용자정보 Constants :::::::::::::::::::::::::::::::
export const GET_USERINFO_SAGA = 'apps/ManualManager/ManualMaster/GET_USERINFO_SAGA';
export const SET_USERINFO_REDUCR = 'apps/ManualManager/ManualMaster/SET_USERINFO_REDUCR';
export const SET_SELECTEDUSERINFO_REDUCR = 'apps/ManualManager/ManualMaster/SET_SELECTEDUSERiNFO_REDUCR';
export const GET_SELECTEDUSERINFO_SAGA = 'apps/ManualManager/ManualMaster/GET_SELECTEDUSERINFO_SAGA';
// :::::::::::::::::::::::: 사용자정보 Constants :::::::::::::::::::::::::::::::
