const prefix = 'apps/manual/admin/ManualManager/';
export const INIT_MANUALMANGERBYREDUCR = `${prefix}ManualMaster/INIT_MANUALMANGERBYREDUCR`;
export const SET_MOVEPAGETYPEBYREDUCR = `${prefix}ManualMaster/SET_MOVEPAGETYPEBYREDUCR`;

export const INIT_DEFAULTMGR_REDUCR = `${prefix}ManualMaster/INIT_DEFAULTMGR_REDUCR`;
export const SET_DEFAULTMGRCHANGEVALUE_REDUCR = `${prefix}ManualMaster/SET_DEFAULTMGRCHANGEVALUE_REDUCR`;
export const SET_DEFAULTMGR_REDUCR = `${prefix}ManualMaster/SET_DEFAULTMGR_REDUCR`;
export const GET_DEFAULTMGR_SAGA = `${prefix}ManualMaster/GET_DEFAULTMGR_SAGA`;
export const ADD_DEFAULTMGR_SAGA = `${prefix}ManualMaster/ADD_DEFAULTMGR_SAGA`;
export const MODIFY_DEFUALTMGR_SAGA = `${prefix}ManualMaster/MODIFY_DEFUALTMGR_SAGA`;
export const ADD_TAB_INFO_REDUCR = `${prefix}ManualMaster/ADD_TAB_INFO_REDUCR`;
export const SET_TAB_IDX_REDUCR = `${prefix}ManualMaster/SET_TAB_IDX_REDUCR`;
export const REMOVE_TAB_INFO_REDUCR = `${prefix}ManualMaster/REMOVE_TAB_INFO_REDUCR`;
export const GET_EDITOR_INFO_SAGA = `${prefix}ManualMaster/GET_EDITOR_INFO_SAGA`;
export const SET_EDITORMGR_REDUCR = `${prefix}ManualMaster/SET_EDITORMGR_REDUCR`;
export const SET_IS_EDITORMGR_REDUCR = `${prefix}ManualMaster/SET_IS_EDITORMGR_REDUCR`;
export const SET_PAGE_TYPE_REDUCR = `${prefix}ManualMaster/SET_PAGE_TYPE_REDUCR`;
export const SAVE_EDITOR_SAGA = `${prefix}ManualMaster/SAVE_EDITOR_SAGA`;
export const SET_TAB_NAME_REDUCR = `${prefix}ManualMaster/SET_TAB_NAME_REDUCR`;
export const RESET_EDITORMGR_REDUCR = `${prefix}ManualMaster/RESET_EDITORMGR_REDUCR`;
export const MOVE_TAB_COMPONENT_REDUCR = `${prefix}ManualMaster/MOVE_TAB_COMPONENT_REDUCR`;
export const ADD_EDITOR_COMPONENT_REDUCR = `${prefix}ManualMaster/ADD_EDITOR_COMPONENT_REDUCR`;
export const SET_ADD_EDITOR_COMPONENT_ID_REDUCR = `${prefix}ManualMaster/SET_ADD_EDITOR_COMPONENT_ID_REDUCR`;
export const SET_FOCUS_EDITOR_COMPONENT_IDX_REDUCR = `${prefix}ManualMaster/SET_FOCUS_EDITOR_COMPONENT_IDX_REDUCR`;
export const SET_EDITOR_COMPONENT_VALUE_REDUCR = `${prefix}ManualMaster/SET_EDITOR_COMPONENT_VALUE_REDUCR`;
export const SET_EDITOR_COMPONENT_INDEX_REDUCR = `${prefix}ManualMaster/SET_EDITOR_COMPONENT_INDEX_REDUCR`;
export const REMOVE_EDITOR_COMPONENT_REDUCR = `${prefix}ManualMaster/REMOVE_EDITOR_COMPONENT_REDUCR`;
export const SET_ADD_EDITOR_COMPONENT_IDX_REDUCR = `${prefix}ManualMaster/SET_ADD_EDITOR_COMPONENT_IDX_REDUCR`;
export const SET_EDITOR_COMPONENT_LIST_REDUCR = `${prefix}ManualMaster/SET_EDITOR_COMPONENT_LIST_REDUCR`;
export const REVISION_MANUAL_SAGA = `${prefix}ManualMaster/REVISION_MANUAL_SAGA`;
export const CONFIRM_DEFAULT_MGR_SAGA = `${prefix}ManualMaster/CONFIRM_DEFAULT_MGR_SAGA`;
export const RESET_DEFAULT_MGR_SAGA = `${prefix}ManualMaster/RESET_DEFAULT_MGR_SAGA`;
export const REMOVE_MANUAL_SAGA = `${prefix}ManualMaster/REMOVE_MANUAL_SAGA`;
export const GET_DEFAULTMGR_BY_VERSION_SAGA = `${prefix}ManualMaster/GET_DEFAULTMGR_BY_VERSION_SAGA`;
export const SET_SCROLL_COMPONENT_REDUCR = `${prefix}ManualMaster/SET_SCROLL_COMPONENT_REDUCR`;
export const GET_OPTIONMGR_SAGA = `${prefix}ManualMaster/GET_OPTIONMGR_SAGA`;
export const SET_IS_RELATION_MUAL_MODAL_REDUCR = `${prefix}ManualMaster/SET_IS_RELATION_MUAL_MODAL_REDUCR`;
export const SET_IS_ADD_MUAL_TYPE_MODAL_REDUCR = `${prefix}ManualMaster/SET_IS_ADD_MUAL_TYPE_MODAL_REDUCR`;
export const GET_COMPARE_TEMPLET_SAGA = `${prefix}ManualMaster/GET_COMPARE_TEMPLET_SAGA`;
export const SET_COMPARE_TEMPLET_REDUCR = `${prefix}ManualMaster/SET_COMPARE_TEMPLET_REDUCR`;
export const SET_COMPARE_TEMPLET_VIEW_MODE_REDUCR = `${prefix}ManualMaster/SET_COMPARE_TEMPLET_VIEW_MODE_REDUCR`;
export const SAVE_COMPARE_TEMPLET = `${prefix}ManualMaster/SAVE_COMPARE_TEMPLET`;
export const SET_COMPARE_TEMPLET_CHANGE_VALUE_REDUCR = `${prefix}ManualMaster/SET_COMPARE_TEMPLET_CHANGE_VALUE_REDUCR`;
export const SET_COMPARE_TEMPLET_HOVER_KEY_REDUCR = `${prefix}ManualMaster/SET_COMPARE_TEMPLET_HOVER_KEY_REDUCR`;
export const SET_COMPARE_TEMPLET_CONTENT_NAME_REDUCR = `${prefix}ManualMaster/SET_COMPARE_TEMPLET_CONTENT_NAME_REDUCR`;
export const REMOVE_COMPARE_TEMPLET_CONTENT_ITEM_REDUCR = `${prefix}ManualMaster/REMOVE_COMPARE_TEMPLET_CONTENT_ITEM_REDUCR`;
export const ADD_COMPARE_TEMPLET_CONTENT_ITEM_REDUCR = `${prefix}ManualMaster/ADD_COMPARE_TEMPLET_CONTENT_ITEM_REDUCR`;
export const MOVE_COMPARE_TEMPLET_CONTENT_ITEM_REDUCR = `${prefix}ManualMaster/MOVE_COMPARE_TEMPLET_CONTENT_ITEM_REDUCR`;
export const GET_COMPARE_MGR_SAGA = `${prefix}ManualMaster/GET_COMPARE_MGR_SAGA`;
export const SET_COMPARE_MANAGE_TEMPLET_REDUCR = `${prefix}ManualMaster/SET_COMPARE_MANAGE_TEMPLET_REDUCR`;
export const SET_COMPARE_MANAGE_DATA_REDUCR = `${prefix}ManualMaster/SET_COMPARE_MANAGE_DATA_REDUCR`;
export const SET_COMPARE_MANAGE_CHANGE_VALUE_REDUCR = `${prefix}ManualMaster/SET_COMPARE_MANAGE_CHANGE_VALUE_REDUCR`;
export const SAVE_COMPARE_DATA_SAGA = `${prefix}ManualMaster/SAVE_COMPARE_DATA_SAGA`;
export const SET_SELECTED_COMPARE_MANAGE_IDX_REDUCR = `${prefix}ManualMaster/SET_SELECTED_COMPARE_MANAGE_IDX_REDUCR`;
export const ADD_EDITOR_COMPONENT_VALUE_REDUCR = `${prefix}ManualMaster/ADD_EDITOR_COMPONENT_VALUE_REDUCR`;
export const REMOVE_EDITOR_COMPONENT_VALUE_REDUCR = `${prefix}ManualMaster/REMOVE_EDITOR_COMPONENT_VALUE_REDUCR`;
export const SET_IS_INDEX_RELATION_MODAL_REDUCR = `${prefix}ManualMaster/SET_IS_INDEX_RELATION_MODAL_REDUCR`;
export const GET_INDEX_RELATION_MANUAL_LIST_SAGA = `${prefix}ManualMaster/GET_INDEX_RELATION_MANUAL_LIST_SAGA`;
export const SET_INDEX_RELATION_MANUAL_LIST_REDUCR = `${prefix}ManualMaster/SET_INDEX_RELATION_MANUAL_LIST_REDUCR`;
export const GET_INDEX_RELATION_COMPONENT_LIST_SAGA = `${prefix}ManualMaster/GET_INDEX_RELATION_COMPONENT_LIST_SAGA`;
export const SET_INDEX_RELATION_COMPONENT_LIST_REDUCR = `${prefix}ManualMaster/SET_INDEX_RELATION_COMPONENT_LIST_REDUCR`;
export const SET_INDEX_RELATION_COMPONENT_ITEM_REDUCR = `${prefix}ManualMaster/SET_INDEX_RELATION_COMPONENT_ITEM_REDUCR`;
export const SET_INDEX_RELATION_LIST_REDUCR = `${prefix}ManualMaster/SET_INDEX_RELATION_LIST_REDUCR`;
export const SET_EDITOR_PARAGRAPH_REDUCR = `${prefix}ManualMaster/SET_EDITOR_PARAGRAPH_REDUCR`;
export const GET_CONTENT_SECURITY_LIST_SAGA = `${prefix}ManualMaster/GET_CONTENT_SECURITY_LIST_SAGA`;
export const SET_CONTENT_SECURITY_LIST_REDUCR = `${prefix}ManualMaster/SET_CONTENT_SECURITY_LIST_REDUCR`;
export const SET_IS_SECURITY_MODAL_REDUCR = `${prefix}ManualMaster/SET_IS_SECURITY_MODAL_REDUCR`;
export const SET_SECURITY_SELECT_DATA_REDUCR = `${prefix}ManualMaster/SET_SECURITY_SELECT_DATA_REDUCR`;
export const GET_SECURITY_SELECT_DATA_SAGA = `${prefix}ManualMaster/GET_SECURITY_SELECT_DATA_SAGA`;
export const SAVE_CONTENT_SECURITY_SAGA = `${prefix}ManualMaster/SAVE_CONTENT_SECURITY_SAGA`;
export const REMOVE_CONTENT_SECURITY_SAGA = `${prefix}ManualMaster/REMOVE_CONTENT_SECURITY_ROW_SAGA`;
export const REMOVE_CATEGORY_INFO_SAGA = `${prefix}ManualMaster/REMOVE_CONTENT_SECURITY_ROW_SAGA`;

// :::::::::::::::::::::::: 사용자정보 Constants :::::::::::::::::::::::::::::::
export const GET_USERINFO_SAGA = `${prefix}ManualMaster/GET_USERINFO_SAGA`;
export const SET_USERINFO_REDUCR = `${prefix}ManualMaster/SET_USERINFO_REDUCR`;
export const SET_SELECTEDUSERINFO_REDUCR = `${prefix}ManualMaster/SET_SELECTEDUSERiNFO_REDUCR`;
export const GET_SELECTEDUSERINFO_SAGA = `${prefix}ManualMaster/GET_SELECTEDUSERINFO_SAGA`;
// :::::::::::::::::::::::: 사용자정보 Constants :::::::::::::::::::::::::::::::

// :::::::::::::::::::::::: 관련정보 ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
export const GET_CATEGORYLIST = `${prefix}OptionMgr/RelactionManualList/GET_CATEGORYLIST`;
export const GET_MANUALLIST_INFO_SAGA = `${prefix}OptionMgr/GET_MANUALLIST_INFO_SAGA`;
export const SET_CATEGORYLIST_REDUCR = `${prefix}OptionMgr/RelactionManualList/SET_CATEGORYLIST_REDUCR`;
export const SET_RELATIONCATEGORYIDX = `${prefix}OptionMgr/RelactionManualList/SET_RELATIONCATEGORYIDX`;
export const GET_RELATIONMANUALLIST_SAGA = `${prefix}OptionMgr/RelactionManualList/GET_RELATIONMANUALLIST_SAGA`;
export const SET_RELATIONMANUALLIST_REDUCR = `${prefix}OptionMgr/RelactionManualList/SET_RELATIONMANUALLIST_REDUCR`;
export const SET_RELATIONMANUALLIST_SAGA = `${prefix}OptionMgr/RelactionManualList/SET_RELATIONMANUALLIST_SAGA`;
export const SET_SELECTEDRELATIONMANUAL_REDUCR = `${prefix}OptionMgr/RelactionManualList/SET_SELECTEDRELATIONMANUAL_REDUCR`;
export const SET_RELATIONMANUALLISTBYMUALIDX_REDUCR = `${prefix}OptionMgr/RelactionManualList/SET_RELATIONMANUALLISTBYMUALIDX_REDUCR`;
// :::::::::::::::::::::::: 관련정보 :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

// :::::::::::::::::::::::: 에디터 미리보기 ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
export const SET_PREVIEW_MODAL_REDUCR = 'apps/manual/admin/ManualManager/ManualMaster/SET_PREVIEW_MODAL_REDUCR';
// :::::::::::::::::::::::: 에디터 미리보기 ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
