const base = 'containers/admin/AdminMain/Classify/RootMap';
export const GET_ROOTMAP_LIST = `${base}/GET_ROOTMAP_LIST`;
export const SET_ROOTMAP_LIST = `${base}/SET_ROOTMAP_LIST`;
export const SET_VISIBLE_MODAL = `${base}/SET_VISIBLE_MODAL`;
export const ADD_ROOTMAP = `${base}/ADD_ROOTMAP`;
export const UPDATE_ROOTMAP = `${base}/UPDATE_ROOTMAP`;
export const DELETE_ROOTMAP = `${base}/DELETE_ROOTMAP`;
export const SET_SELECTED_ROW_KEYS = `${base}/SET_SELECTED_ROW_KEYS`;
export const SET_SELECTED_ROOTMAP = `${base}/SET_SELECTED_ROOTMAP`;
