export const LOADING_SAFEWORK_CONNECT_SEARCH_SAGA = 'apps/hyPm/InformNote/note/LOADING_SAFEWORK_CONNECT_SEARCH_SAGA';
export const LOADING_SAFEWORK_CONNECT_SEARCH = 'apps/hyPm/InformNote/note/LOADING_SAFEWORK_CONNECT_SEARCH';
