export default {
  common: {
    position: 'fixed',
    zIndex: '2',
    padding: 0,
    margin: '0 20px 20px 230px',
    width: 'calc(100% - 250px)',
    top: '50%',
    left: 0,
    transform: 'translateY(-50%)',
    border: 'none',
  },
  password: {
    maxWidth: 420,
    height: 222,
    margin: 0,
    left: 'calc(50% - 210px)',
  },
  tableView: {
    width: 'calc(80% - 2px)',
    border: '1px solid #d4d7df',
    background: '#ffffff',
    boxShadow: '3px 3px 3px rgba(0,0,0,.05)',
  },
  formView: {
    maxWidth: '80%',
    margin: 0,
    left: 'calc(50% - 40%)',
    background: '#ffffff',
  },
  searchEquipView: {
    maxWidth: '80%',
    height: 570,
    margin: 0,
    left: 'calc(50% - 40%)',
    background: '#ffffff',
    // maxHeight: 650,
    // overflow: 'hidden',
  },
  employeeSelectorView: {
    maxWidth: '60%',
    height: 570,
    margin: 0,
    left: 'calc(50% - 30%)',
    background: '#ffffff',
    // maxHeight: 650,
    // overflow: 'hidden',
  },
};
