export const dummyData = [
  {
    WORK_SEQ: 132,
    WORK_ID: 'SAMPLE_WORK1',
    NAME_KOR: 'SAMPLE_WORK1',
    NAME_ENG: '',
    NAME_CHN: '',
    NAME_JPN: '',
    NAME_ETC: '',
    DSCR: '극한 업무',
    STATUS: 0,
    REG_USER_ID: 15125125,
    REG_DTTM: new Date().getTime(),
    UPD_USER_ID: 15125125,
    UPD_DTTM: new Date().getTime(),
    APP_ID: -1,
    CATEGORY_ID: -1,
  },
  {
    WORK_SEQ: 133,
    WORK_ID: 'SAMPLE_WORK2',
    NAME_KOR: 'SAMPLE_WORK2',
    NAME_ENG: '',
    NAME_CHN: '',
    NAME_JPN: '',
    NAME_ETC: '',
    DSCR: '빡센 업무',
    STATUS: 0,
    REG_USER_ID: 15125125,
    REG_DTTM: new Date().getTime(),
    UPD_USER_ID: 15125125,
    UPD_DTTM: new Date().getTime(),
    APP_ID: 333,
    CATEGORY_ID: -1,
  },
  {
    WORK_SEQ: 134,
    WORK_ID: 'SAMPLE_WORK3',
    NAME_KOR: 'SAMPLE_WORK3',
    NAME_ENG: '',
    NAME_CHN: '',
    NAME_JPN: '',
    NAME_ETC: '',
    DSCR: '편한 업무',
    STATUS: 0,
    REG_USER_ID: 15125125,
    REG_DTTM: new Date().getTime(),
    UPD_USER_ID: 15125125,
    UPD_DTTM: new Date().getTime(),
    APP_ID: 222,
    CATEGORY_ID: -1,
  },
  {
    WORK_SEQ: 135,
    WORK_ID: 'SAMPLE_WORK4',
    NAME_KOR: 'SAMPLE_WORK4',
    NAME_ENG: '',
    NAME_CHN: '',
    NAME_JPN: '',
    NAME_ETC: '',
    DSCR: '힘든 업무',
    STATUS: 0,
    REG_USER_ID: 15125125,
    REG_DTTM: new Date().getTime(),
    UPD_USER_ID: 15125125,
    UPD_DTTM: new Date().getTime(),
    APP_ID: 111,
    CATEGORY_ID: -1,
  },
];
