export const GET_BIZBUILDERLIST_BYSAGA = 'apps/manual/user/BizBuilderWidget/GET_BIZBUILDERLIST_BYSAGA';
export const SET_BIZBUILDERLIST_BYREDUCR = 'apps/manual/user/BizBuilderWidget/SET_BIZBUILDERLIST_BYREDUCR';
export const GET_BIZBULDERLISTWIDGET_SETTINGINFO_BYSAGA = 'apps/manual/user/BizBuilderWidget/GET_BIZBULDERLISTWIDGET_SETTINGINFO_BYSAGA';
export const SET_BIZBULDERLISTWIDGET_SETTINGINFO_BYREDUCR = 'apps/manual/user/BizBuilderWidget/SET_BIZBULDERLISTWIDGET_SETTINGINFO_BYREDUCR';
export const GET_BIZBUILDERVIEW_BYSAGA = 'apps/manual/user/BizBuilderWidget/GET_BIZBUILDERVIEW_BYSAGA';
export const SET_BIZBUILDERVIEW_BYREDUCR = 'apps/manual/user/BizBuilderWidget/SET_BIZBUILDERVIEW_BYREDUCR';
