import { useState, useEffect } from 'react';

const noneOption = {
  colSpan: 0,
  rowSpan: 0,
  className: 'hide',
};

const filterOption = {
  byIndex: [13, 14, 25, 26, 27, 28, 29, 30],
};

const useHooks = ({ updateData }) => {
  // Mode - 'read', 'write'
  const [mode, setMode] = useState('write');
  const [grid, setGrid] = useState([
    [
      { value: '구 분', readOnly: true },
      { value: '항 목', colSpan: 2, readOnly: true },
      { value: '항 목', readOnly: true, ...noneOption },
      { value: '금일지침', readOnly: true },
      { value: '전일지침', readOnly: true },
      { value: '일사용량', readOnly: true },
      { value: '월간누계', readOnly: true },
      { value: '일 평균', readOnly: true },
      { value: '', readOnly: true },
    ],
    [
      { value: '', readOnly: true },
      { value: '', readOnly: true },
      { value: 'FAB-1', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '공업용수', readOnly: true },
      { value: '', readOnly: true },
      { value: 'FAB-2', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '', readOnly: true },
      { value: 'C-1동 소계', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '사용량', readOnly: true },
      { value: 'UPW SYSTEM', readOnly: true },
      { value: 'FAB-4', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '( Veolia )', readOnly: true },
      { value: 'FAB-5', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '(㎥/일)', readOnly: true },
      { value: '', readOnly: true },
      { value: 'C-2동 소계', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '', readOnly: true },
      { value: 'FAB-7(MB)', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '', readOnly: true },
      { value: 'B-1', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '', readOnly: true },
      { value: 'C-3동 소계', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '', readOnly: true },
      { value: 'UPW 용수 총소계', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '총 공수 MAIN', colSpan: 2, readOnly: true },
      { value: '총 공수 MAIN', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],

    [
      { value: '시수사용량', readOnly: true },
      { value: 'WWT(Veolia)', rowSpan: 4, readOnly: true },
      { value: 'WWT-1(C-3)', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'WWT(Veolia)', readOnly: true, ...noneOption },
      { value: 'WWT-2(C-3)', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'WWT(Veolia)', readOnly: true, ...noneOption },
      { value: 'WWT-3(C-1)', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'WWT(Veolia)', readOnly: true, ...noneOption },
      { value: '소계', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '(㎥/일)', readOnly: true },
      { value: '총 시수 MAIN', colSpan: 2, readOnly: true },
      { value: '총 시수 MAIN', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],

    [
      { value: '', readOnly: true },
      { value: 'C-1/C-3동 혼합', colSpan: 2, readOnly: true },
      { value: 'C-1/C-3동 혼합', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '오 수', readOnly: true },
      { value: 'C-2동', colSpan: 2, readOnly: true },
      { value: 'C-2동', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '발생량', readOnly: true },
      { value: '남자  기숙사', colSpan: 2, readOnly: true },
      { value: '남자  기숙사', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '(㎥/일)', readOnly: true },
      { value: '여자  기숙사', colSpan: 2, readOnly: true },
      { value: '여자  기숙사', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'R 동', colSpan: 2, readOnly: true },
      { value: 'R 동', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '1공장 오수 총소계', colSpan: 2, readOnly: true },
      { value: '1공장 오수 총소계', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '자재통합창고동(신규)', colSpan: 2, readOnly: true },
      { value: '자재통합창고동(신규)', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '안전보건센터(신규)', colSpan: 2, readOnly: true },
      { value: '안전보건센터(신규)', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],

    [
      { value: '', readOnly: true },
      { value: 'C-1', rowSpan: 6, readOnly: true },
      { value: 'HF-C ①', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-1', readOnly: true, ...noneOption },
      { value: 'HF-R ②', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-1', readOnly: true, ...noneOption },
      { value: '연마계 ③', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-1', readOnly: true, ...noneOption },
      { value: '중금속 ④', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-1', readOnly: true, ...noneOption },
      { value: '과산화수소 ⑤', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-1', readOnly: true, ...noneOption },
      { value: '소    계 ⑥', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],

    [
      { value: '폐 수', readOnly: true },
      { value: 'C-2', rowSpan: 5, readOnly: true },
      { value: '유기계 ⑴', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '처리량', readOnly: true },
      { value: 'C-2', readOnly: true, ...noneOption },
      { value: '불소계 ⑵', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '(㎥/일)', readOnly: true },
      { value: 'C-2', readOnly: true, ...noneOption },
      { value: '산/알카리 ⑶', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-2', readOnly: true, ...noneOption },
      { value: '소   계 ⑷', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-2', readOnly: true, ...noneOption },
      { value: '방류량:TMS⑸', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],

    [
      { value: '', readOnly: true },
      { value: 'C-3', rowSpan: 11, readOnly: true },
      { value: '불소계 ⓐ', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-3', readOnly: true, ...noneOption },
      { value: 'A/A-C', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-3', readOnly: true, ...noneOption },
      { value: 'A/A-R ⓒ', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-3', readOnly: true, ...noneOption },
      { value: '유기계 ⓓ', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-3', readOnly: true, ...noneOption },
      { value: 'CMP ⓔ', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-3', readOnly: true, ...noneOption },
      { value: 'MAP(전처리)', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-3', readOnly: true, ...noneOption },
      { value: 'TMAH(전처리)', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-3', readOnly: true, ...noneOption },
      { value: '소계ⓕ', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-3', readOnly: true, ...noneOption },
      { value: '소계ⓖ(C-1+C-3)', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-3', readOnly: true, ...noneOption },
      { value: '재사용량', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-3', readOnly: true, ...noneOption },
      { value: '방류량:TMSⓗ', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '폐수 총 유입량', colSpan: 2, readOnly: true },
      { value: '폐수 총 유입량', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: '폐수 총 방류량', colSpan: 2, readOnly: true },
      { value: '폐수 총 방류량', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],

    [
      { value: '', readOnly: true },
      { value: 'C-1/C-2 UPW', rowSpan: 3, readOnly: true },
      { value: 'SUMP', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-1/C-2 UPW', readOnly: true, ...noneOption },
      { value: 'Waste Water', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-1/C-2 UPW', readOnly: true, ...noneOption },
      { value: '소 계', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],

    [
      { value: '폐 수', readOnly: true },
      { value: 'C-3 UPW', rowSpan: 3, readOnly: true },
      { value: 'SUMP', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '발생량', readOnly: true },
      { value: 'C-3 UPW', readOnly: true, ...noneOption },
      { value: 'Waste Water', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '구 분', readOnly: true },
      { value: 'C-3 UPW', readOnly: true, ...noneOption },
      { value: '소 계', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],

    [
      { value: '(㎥/일)', readOnly: true },
      { value: 'System IC내 Hynix 폐수', rowSpan: 3, readOnly: true },
      { value: 'Maskshop 폐수', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'System IC내 Hynix 폐수', readOnly: true, ...noneOption },
      { value: 'PKG 폐수', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'System IC내 Hynix 폐수', readOnly: true, ...noneOption },
      { value: '소 계', readOnly: true },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],

    [
      { value: '', readOnly: true },
      { value: 'Veolia 폐수 총 발생량', colSpan: 2, readOnly: true },
      { value: '소 계', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'Magnachip 폐수 총 발생량', colSpan: 2, readOnly: true },
      { value: '소 계', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'Hynix 폐수 총 발생량', colSpan: 2, readOnly: true },
      { value: '소 계', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'System IC 폐수 총 발생량', colSpan: 2, readOnly: true },
      { value: '소 계', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
    [
      { value: '', readOnly: true },
      { value: 'C-3 불소계 폐수 C-1 Back-up량', colSpan: 2, readOnly: true },
      { value: '소 계', readOnly: true, ...noneOption },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
      { value: '' },
    ],
  ]);

  // Grid가 변할때 마다 updateData 함수 호출
  useEffect(() => {
    if (typeof updateData === 'function') {
      updateData(grid);
    }
  }, [grid, updateData]);

  // Cell Change Method
  const onChangedCells = changes => {
    setGrid(prevGrid => {
      const grid = prevGrid.map(row => [...row]);
      changes.forEach(({ cell, row, col, value }) => {
        grid[row][col] = { ...grid[row][col], value };
      });
      return grid;
    });
  };

  // 조회시 참고 Method
  const getFilteredGrid = () =>
    grid
      .filter((row, rowIndex) => !filterOption?.byIndex?.includes(rowIndex))
      .map((row, rowIndex) => {
        console.debug(row);
        // 일부 필터된 데이터 상세 조정
        if (rowIndex === 12) {
          return [
            ...row.slice(0, 1),
            {
              ...row[1],
              rowSpan: 2,
            },
            ...row.slice(2),
          ].map(obj => ({ ...obj, readOnly: true }));
        }
        return [...row].map(obj => ({ ...obj, readOnly: true }));
      });

  const onClickWrite = () => setMode('write');

  const onClickRead = () => setMode('read');

  return { mode, grid, filteredGrid: getFilteredGrid(), action: { onChangedCells, onClickRead, onClickWrite } };
};

export default useHooks;
