export const searchedUsers = [
  {
    USER_ID: 73619,
    EMP_NO: 'HSJEON',
    NAME_KOR: '전홍식',
    NAME_ENG: null,
    NAME_CHN: null,
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'hsjeon@kb-sys.co.kr',
    DEPT_ID: 73606,
    DEPT_NAME_KOR: '구축개발본부',
    DEPT_NAME_ENG: '@구축개발본부',
    DEPT_NAME_CHN: '@@구축개발본부',
    DEPT_NAME_JPN: '@@구축개발본부',
    DEPT_NAME_ETC: '@@구축개발본부',
    PSTN_ID: 67631,
    PSTN_NAME_KOR: '이사',
    PSTN_NAME_ENG: '이사',
    PSTN_NAME_CHN: '이사',
    PSTN_NAME_JPN: '이사',
    PSTN_NAME_ETC: '이사',
    DUTY_ID: 2958,
    DUTY_NAME_KOR: '본부장',
    DUTY_NAME_ENG: '@본부장',
    DUTY_NAME_CHN: '@@본부장',
    DUTY_NAME_JPN: '본부장',
    DUTY_NAME_ETC: '본부장',
    PHOTO: ' ',
    OFFICE_TEL_NO: null,
    MOBILE_TEL_NO: null,
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
  {
    USER_ID: 1,
    EMP_NO: 'ADMIN',
    NAME_KOR: '관리자',
    NAME_ENG: 'ADMINISTRATOR',
    NAME_CHN: 'ADMINISTRATOR',
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'ADMIN@KB-SYS.CO.KR',
    DEPT_ID: 1001,
    DEPT_NAME_KOR: 'KB-SYS',
    DEPT_NAME_ENG: 'KB-SYS',
    DEPT_NAME_CHN: 'KB-SYS',
    DEPT_NAME_JPN: 'KB-SYS',
    DEPT_NAME_ETC: 'KB-SYS',
    PSTN_ID: 2508,
    PSTN_NAME_KOR: 'KB-SYS',
    PSTN_NAME_ENG: '@KB-SYS',
    PSTN_NAME_CHN: '@@KB-SYS',
    PSTN_NAME_JPN: '@@@KB-SYS',
    PSTN_NAME_ETC: '@@@@KB-SYS',
    DUTY_ID: 2909,
    DUTY_NAME_KOR: 'KB-SYS',
    DUTY_NAME_ENG: '@KB-SYS',
    DUTY_NAME_CHN: '@@KB-SYS',
    DUTY_NAME_JPN: '@@@KB-SYS',
    DUTY_NAME_ETC: '@@@@@KB-SYS',
    PHOTO: ' ',
    OFFICE_TEL_NO: null,
    MOBILE_TEL_NO: null,
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
  {
    USER_ID: 73615,
    EMP_NO: 'JHKIM',
    NAME_KOR: '김준혁',
    NAME_ENG: null,
    NAME_CHN: null,
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'jhkim@kb-sys.co.kr',
    DEPT_ID: 73610,
    DEPT_NAME_KOR: 'MSA',
    DEPT_NAME_ENG: '@MSA',
    DEPT_NAME_CHN: '@@MSA',
    DEPT_NAME_JPN: '@@MSA',
    DEPT_NAME_ETC: '@@MSA',
    PSTN_ID: 60703,
    PSTN_NAME_KOR: '책임 연구원',
    PSTN_NAME_ENG: '책임 연구원',
    PSTN_NAME_CHN: '책임 연구원',
    PSTN_NAME_JPN: '책임 연구원',
    PSTN_NAME_ETC: '책임 연구원',
    DUTY_ID: 60965,
    DUTY_NAME_KOR: '팀원',
    DUTY_NAME_ENG: '팀원',
    DUTY_NAME_CHN: '팀원',
    DUTY_NAME_JPN: '팀원',
    DUTY_NAME_ETC: '팀원',
    PHOTO: ' ',
    OFFICE_TEL_NO: null,
    MOBILE_TEL_NO: null,
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
  {
    USER_ID: 73616,
    EMP_NO: 'SYLEE',
    NAME_KOR: '이숙영',
    NAME_ENG: null,
    NAME_CHN: null,
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'sylee@kb-sys.co.kr',
    DEPT_ID: 73610,
    DEPT_NAME_KOR: 'MSA',
    DEPT_NAME_ENG: '@MSA',
    DEPT_NAME_CHN: '@@MSA',
    DEPT_NAME_JPN: '@@MSA',
    DEPT_NAME_ETC: '@@MSA',
    PSTN_ID: 60732,
    PSTN_NAME_KOR: '선임연구원',
    PSTN_NAME_ENG: '선임연구원',
    PSTN_NAME_CHN: '선임연구원',
    PSTN_NAME_JPN: '선임연구원',
    PSTN_NAME_ETC: '선임연구원',
    DUTY_ID: 60965,
    DUTY_NAME_KOR: '팀원',
    DUTY_NAME_ENG: '팀원',
    DUTY_NAME_CHN: '팀원',
    DUTY_NAME_JPN: '팀원',
    DUTY_NAME_ETC: '팀원',
    PHOTO: ' ',
    OFFICE_TEL_NO: null,
    MOBILE_TEL_NO: null,
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
  {
    USER_ID: 73617,
    EMP_NO: 'JHJUNG',
    NAME_KOR: '정종훈',
    NAME_ENG: null,
    NAME_CHN: null,
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'jhjung@kb-sys.co.kr',
    DEPT_ID: 73607,
    DEPT_NAME_KOR: '연구소',
    DEPT_NAME_ENG: '@연구소',
    DEPT_NAME_CHN: '@@연구소',
    DEPT_NAME_JPN: '@@연구소',
    DEPT_NAME_ETC: '@@연구소',
    PSTN_ID: 60703,
    PSTN_NAME_KOR: '책임 연구원',
    PSTN_NAME_ENG: '책임 연구원',
    PSTN_NAME_CHN: '책임 연구원',
    PSTN_NAME_JPN: '책임 연구원',
    PSTN_NAME_ETC: '책임 연구원',
    DUTY_ID: 60965,
    DUTY_NAME_KOR: '팀원',
    DUTY_NAME_ENG: '팀원',
    DUTY_NAME_CHN: '팀원',
    DUTY_NAME_JPN: '팀원',
    DUTY_NAME_ETC: '팀원',
    PHOTO: ' ',
    OFFICE_TEL_NO: null,
    MOBILE_TEL_NO: null,
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
  {
    USER_ID: 73618,
    EMP_NO: 'YJYANG',
    NAME_KOR: '양영진',
    NAME_ENG: null,
    NAME_CHN: null,
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'yjyang@kb-sys.co.kr',
    DEPT_ID: 73605,
    DEPT_NAME_KOR: '마케팅전략본부',
    DEPT_NAME_ENG: '@마케팅전략본부',
    DEPT_NAME_CHN: '@@마케팅전략본부',
    DEPT_NAME_JPN: '@@마케팅전략본부',
    DEPT_NAME_ETC: '@@마케팅전략본부',
    PSTN_ID: 67631,
    PSTN_NAME_KOR: '이사',
    PSTN_NAME_ENG: '이사',
    PSTN_NAME_CHN: '이사',
    PSTN_NAME_JPN: '이사',
    PSTN_NAME_ETC: '이사',
    DUTY_ID: 2958,
    DUTY_NAME_KOR: '본부장',
    DUTY_NAME_ENG: '@본부장',
    DUTY_NAME_CHN: '@@본부장',
    DUTY_NAME_JPN: '본부장',
    DUTY_NAME_ETC: '본부장',
    PHOTO: ' ',
    OFFICE_TEL_NO: null,
    MOBILE_TEL_NO: null,
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
  {
    USER_ID: 73620,
    EMP_NO: 'SIBAE',
    NAME_KOR: '배승인',
    NAME_ENG: null,
    NAME_CHN: null,
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'sibae@kb-sys.co.kr',
    DEPT_ID: 73604,
    DEPT_NAME_KOR: '경영지원본부',
    DEPT_NAME_ENG: '@경영지원본부',
    DEPT_NAME_CHN: '@@경영지원본부',
    DEPT_NAME_JPN: '@@경영지원본부',
    DEPT_NAME_ETC: '@@경영지원본부',
    PSTN_ID: 60702,
    PSTN_NAME_KOR: '차장',
    PSTN_NAME_ENG: '차장',
    PSTN_NAME_CHN: '차장',
    PSTN_NAME_JPN: '차장',
    PSTN_NAME_ETC: '차장',
    DUTY_ID: 60965,
    DUTY_NAME_KOR: '팀원',
    DUTY_NAME_ENG: '팀원',
    DUTY_NAME_CHN: '팀원',
    DUTY_NAME_JPN: '팀원',
    DUTY_NAME_ETC: '팀원',
    PHOTO: ' ',
    OFFICE_TEL_NO: null,
    MOBILE_TEL_NO: null,
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
  {
    USER_ID: 73621,
    EMP_NO: 'KBKIM',
    NAME_KOR: '김기백',
    NAME_ENG: null,
    NAME_CHN: null,
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'kbkim@kb-sys.co.kr',
    DEPT_ID: 1001,
    DEPT_NAME_KOR: 'KB-SYS',
    DEPT_NAME_ENG: 'KB-SYS',
    DEPT_NAME_CHN: 'KB-SYS',
    DEPT_NAME_JPN: 'KB-SYS',
    DEPT_NAME_ETC: 'KB-SYS',
    PSTN_ID: 67629,
    PSTN_NAME_KOR: '대표이사',
    PSTN_NAME_ENG: '대표이사',
    PSTN_NAME_CHN: '대표이사',
    PSTN_NAME_JPN: '대표이사',
    PSTN_NAME_ETC: '대표이사',
    DUTY_ID: 2929,
    DUTY_NAME_KOR: '대표이사',
    DUTY_NAME_ENG: '대표이사',
    DUTY_NAME_CHN: '대표이사',
    DUTY_NAME_JPN: '대표이사',
    DUTY_NAME_ETC: '대표이사',
    PHOTO: ' ',
    OFFICE_TEL_NO: null,
    MOBILE_TEL_NO: null,
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
  {
    USER_ID: 73613,
    EMP_NO: 'SMLEE',
    NAME_KOR: '이상민',
    NAME_ENG: null,
    NAME_CHN: null,
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'smlee@kb-sys.co.kr',
    DEPT_ID: 73610,
    DEPT_NAME_KOR: 'MSA',
    DEPT_NAME_ENG: '@MSA',
    DEPT_NAME_CHN: '@@MSA',
    DEPT_NAME_JPN: '@@MSA',
    DEPT_NAME_ETC: '@@MSA',
    PSTN_ID: 60677,
    PSTN_NAME_KOR: '수석',
    PSTN_NAME_ENG: '수석',
    PSTN_NAME_CHN: '수석',
    PSTN_NAME_JPN: '수석',
    PSTN_NAME_ETC: '수석',
    DUTY_ID: 60965,
    DUTY_NAME_KOR: '팀원',
    DUTY_NAME_ENG: '팀원',
    DUTY_NAME_CHN: '팀원',
    DUTY_NAME_JPN: '팀원',
    DUTY_NAME_ETC: '팀원',
    PHOTO: ' ',
    OFFICE_TEL_NO: null,
    MOBILE_TEL_NO: null,
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
  {
    USER_ID: 73614,
    EMP_NO: 'ICYU',
    NAME_KOR: '유인찬',
    NAME_ENG: null,
    NAME_CHN: null,
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'icyu@kb-sys.co.kr',
    DEPT_ID: 73610,
    DEPT_NAME_KOR: 'MSA',
    DEPT_NAME_ENG: '@MSA',
    DEPT_NAME_CHN: '@@MSA',
    DEPT_NAME_JPN: '@@MSA',
    DEPT_NAME_ETC: '@@MSA',
    PSTN_ID: 60703,
    PSTN_NAME_KOR: '책임 연구원',
    PSTN_NAME_ENG: '책임 연구원',
    PSTN_NAME_CHN: '책임 연구원',
    PSTN_NAME_JPN: '책임 연구원',
    PSTN_NAME_ETC: '책임 연구원',
    DUTY_ID: 60965,
    DUTY_NAME_KOR: '팀원',
    DUTY_NAME_ENG: '팀원',
    DUTY_NAME_CHN: '팀원',
    DUTY_NAME_JPN: '팀원',
    DUTY_NAME_ETC: '팀원',
    PHOTO: ' ',
    OFFICE_TEL_NO: null,
    MOBILE_TEL_NO: null,
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
  {
    USER_ID: 51181,
    EMP_NO: 'X0101006',
    NAME_KOR: '이용혁',
    NAME_ENG: '이용혁',
    NAME_CHN: '이용혁',
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'FYVYKIR@company.com',
    DEPT_ID: 73607,
    DEPT_NAME_KOR: '연구소',
    DEPT_NAME_ENG: '@연구소',
    DEPT_NAME_CHN: '@@연구소',
    DEPT_NAME_JPN: '@@연구소',
    DEPT_NAME_ETC: '@@연구소',
    PSTN_ID: 60669,
    PSTN_NAME_KOR: '상무',
    PSTN_NAME_ENG: '상무',
    PSTN_NAME_CHN: '상무',
    PSTN_NAME_JPN: '상무',
    PSTN_NAME_ETC: '상무',
    DUTY_ID: 2977,
    DUTY_NAME_KOR: '소장',
    DUTY_NAME_ENG: '@소장',
    DUTY_NAME_CHN: '@@소장',
    DUTY_NAME_JPN: '소장',
    DUTY_NAME_ETC: '소장',
    PHOTO: ' ',
    OFFICE_TEL_NO: '02-1234-1234',
    MOBILE_TEL_NO: '010-1234-1234',
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
  {
    USER_ID: 73584,
    EMP_NO: 'JDLEE',
    NAME_KOR: '이재덕',
    NAME_ENG: 'Lee Jaedeok',
    NAME_CHN: '李載德',
    NAME_JPN: null,
    NAME_ETC: null,
    EMAIL: 'jdlee@kb-sys.co.kr',
    DEPT_ID: 73607,
    DEPT_NAME_KOR: '연구소',
    DEPT_NAME_ENG: '@연구소',
    DEPT_NAME_CHN: '@@연구소',
    DEPT_NAME_JPN: '@@연구소',
    DEPT_NAME_ETC: '@@연구소',
    PSTN_ID: 60703,
    PSTN_NAME_KOR: '책임 연구원',
    PSTN_NAME_ENG: '책임 연구원',
    PSTN_NAME_CHN: '책임 연구원',
    PSTN_NAME_JPN: '책임 연구원',
    PSTN_NAME_ETC: '책임 연구원',
    DUTY_ID: 3006,
    DUTY_NAME_KOR: '직장',
    DUTY_NAME_ENG: '직장',
    DUTY_NAME_CHN: '직장',
    DUTY_NAME_JPN: '직장',
    DUTY_NAME_ETC: '직장',
    PHOTO: ' ',
    OFFICE_TEL_NO: null,
    MOBILE_TEL_NO: null,
    COMP_CD: '1000',
    SUB_EMP_NO: null,
    SUB_COMP_CD: null,
    SUB_EMAIL: null,
    EMP_TYPE: 'H',
    DSPT_YN: 'N',
  },
];
