export const LOADING_COLLABORATOR_LIST_SAGA = 'apps/hyPm/PmMobile/LOADING_COLLABORATOR_LIST_SAGA';
export const LOADING_COLLABORATOR_LIST = 'apps/hyPm/PmMobile/LOADING_COLLABORATOR_LIST';

export const UPDATE_COLLABORATOR_LIST_SAGA = 'apps/hyPm/PmMobile/UPDATE_COLLABORATOR_LIST_SAGA';
export const UPDATE_COLLABORATOR_LIST = 'apps/hyPm/PmMobile/UPDATE_COLLABORATOR_LIST';
export const UPDATE_SHEET_INFO_COLLABORATOR_LIST_SAGA = 'apps/hyPm/PmMobile/UPDATE_SHEET_INFO_COLLABORATOR_LIST_SAGA';
