const prefix = 'apps/manual/user/ManualView/';
// get
export const GET_MANUAL_VIEW_SAGA = `${prefix}GET_MANUAL_VIEW_SAGA`;
export const GET_OLD_VERSION_MANUAL_BY_SAGA = `${prefix}GET_OLD_VERSION_MANUAL_BY_SAGA`;
// add

// set
export const SET_MANUAL_VIEW_REDUCR = `${prefix}SET_MANUAL_VIEW_REDUCR`;
export const SET_SELECTED_MUAL_IDX_REDUCR = `${prefix}SET_SELECTED_MUAL_IDX_REDUCR`;
export const SET_SELECTED_TAB_IDX_REDUCR = `${prefix}SET_SELECTED_TAB_IDX_REDUCR`;
export const SET_SELECTED_COMPONENT_IDX_REDUCR = `${prefix}SET_SELECTED_COMPONENT_IDX_REDUCR`;
export const SET_SCROLL_COMPONENT_REDUCR = `${prefix}SET_SCROLL_COMPONENT_REDUCR`;
export const SET_MANUAL_VIEW_HISTORY_REDUCR = `${prefix}SET_MANUAL_VIEW_HISTORY_REDUCR`;
export const SET_MANUAL_BOOKMARK_SAGA = `${prefix}SET_MANUAL_BOOKMARK_SAGA`;
export const SET_MANUAL_BOOKMARK_REDUCR = `${prefix}SET_MANUAL_BOOKMARK_REDUCR`;
export const SET_MANUAL_MASTER_REDUCR = `${prefix}SET_MANUAL_MASTER_REDUCR`;
export const SET_MANUAL_VIEW_NAV_LIST_REDUCR = `${prefix}SET_MANUAL_VIEW_NAV_LIST_REDUCR`;
export const SET_MANUAL_VIEW_RELATION_LIST_REDUCR = `${prefix}SET_MANUAL_VIEW_RELATION_LIST_REDUCR`;
export const SET_MANUAL_VIEW_INFO_REDUCR = `${prefix}SET_MANUAL_VIEW_INFO_REDUCR`;
export const ADD_MANUAL_HISTORY_SAGA = `${prefix}ADD_MANUAL_HISTORY_SAGA`;
export const SET_VIEW_INDEX_RELATION_LIST_REDUCR = `${prefix}SET_VIEW_INDEX_RELATION_LIST_REDUCR`;
export const SET_OLD_VERSION_MANUAL_BY_REDUCR = `${prefix}SET_OLD_VERSION_MANUAL_BY_REDUCR`;

// remove

// etc
export const RESET_MANUAL_VIEW_REDUCR = `${prefix}RESET_MANUAL_VIEW_REDUCR`;
