export const LOADING_USERCOMPANYDEFINE = 'apps/hyPm/Common/LOADING_USERCOMPANYDEFINE';
export const LOADING_USERCOMPANYDEFINE_SAGA = 'apps/hyPm/Common/LOADING_USERCOMPANYDEFINE_SAGA';
export const SEND_INTERLOCKPUSH_SAGA = 'apps/hyPm/Common/SEND_INTERLOCKPUSH_SAGA';

