const defineData = [
  {
    COL_TEXT: 'SDPT',
    COL_ID: 'SDPT',
    USE_YN: 'N',
    LIST_NUM: '1',
    key: '1',
  },
  {
    COL_TEXT: 'F/L',
    COL_ID: 'PLTXT',
    USE_YN: 'N',
    LIST_NUM: '2',
    key: '2',
  },
  {
    COL_TEXT: 'EQ ID',
    COL_ID: 'EQ_ID',
    USE_YN: 'N',
    LIST_NUM: '3',
    key: '3',
  },
  {
    COL_TEXT: 'Model',
    COL_ID: 'MODEL',
    USE_YN: 'N',
    LIST_NUM: '4',
    key: '4',
  },
  {
    COL_TEXT: 'SVID Value',
    COL_ID: 'CURR_VAL',
    USE_YN: 'N',
    LIST_NUM: '5',
    key: '5',
  },
  {
    COL_TEXT: 'Down',
    COL_ID: 'NOTI_TYPE_NAME',
    USE_YN: 'N',
    LIST_NUM: '6',
    key: '6',
  },
  {
    COL_TEXT: 'Down Type',
    COL_ID: 'CODING_NAME',
    USE_YN: 'N',
    LIST_NUM: '7',
    key: '7',
  },
  {
    COL_TEXT: 'Auto/Manual',
    COL_ID: 'IS_MANUAL',
    USE_YN: 'N',
    LIST_NUM: '8',
    key: '8',
  },
  {
    COL_TEXT: 'Down Time',
    COL_ID: 'DOWN_TIME',
    USE_YN: 'N',
    LIST_NUM: '9',
    key: '9',
  },
  {
    COL_TEXT: 'Up Time',
    COL_ID: 'UP_TIME',
    USE_YN: 'N',
    LIST_NUM: '10',
    key: '10',
  },
  {
    COL_TEXT: 'Total Time',
    COL_ID: 'INTERVAL_A',
    USE_YN: 'N',
    LIST_NUM: '11',
    key: '11',
  },
  {
    COL_TEXT: 'Work Time',
    COL_ID: 'INTERVAL_B',
    USE_YN: 'N',
    LIST_NUM: '12',
    key: '12',
  },
  {
    COL_TEXT: 'Down Comment',
    COL_ID: 'NOTE_COMMENT',
    USE_YN: 'N',
    LIST_NUM: '13',
    key: '13',
  },
  {
    COL_TEXT: 'Problem',
    COL_ID: 'ZZPROBLEM',
    USE_YN: 'N',
    LIST_NUM: '14',
    key: '14',
  },
  {
    COL_TEXT: '조치상세내용',
    COL_ID: 'HLTEXT',
    USE_YN: 'N',
    LIST_NUM: '15',
    key: '15',
  },
  {
    COL_TEXT: 'UNIT',
    COL_ID: 'OTEIL_NM',
    USE_YN: 'N',
    LIST_NUM: '16',
    key: '16',
  },
  {
    COL_TEXT: '유형/현상',
    COL_ID: 'FECOD_NM',
    USE_YN: 'N',
    LIST_NUM: '17',
    key: '17',
  },
  {
    COL_TEXT: '원인',
    COL_ID: 'URCOD_NM',
    USE_YN: 'N',
    LIST_NUM: '18',
    key: '18',
  },
  {
    COL_TEXT: '원인부품(군)',
    COL_ID: 'MNCOD_NM',
    USE_YN: 'N',
    LIST_NUM: '19',
    key: '19',
  },
  {
    COL_TEXT: '조치 및 결과',
    COL_ID: 'RESULT',
    USE_YN: 'N',
    LIST_NUM: '20',
    key: '20',
  },
  {
    COL_TEXT: '조치자',
    COL_ID: 'ACTION_BY',
    USE_YN: 'N',
    LIST_NUM: '21',
    key: '21',
  },
  {
    COL_TEXT: 'Last Recipe ID',
    COL_ID: 'LAST_RECIPE_ID',
    USE_YN: 'N',
    LIST_NUM: '22',
    key: '22',
  },
  {
    COL_TEXT: 'Lot ID',
    COL_ID: 'LOT_ID',
    USE_YN: 'N',
    LIST_NUM: '23',
    key: '23',
  },
  {
    COL_TEXT: 'Wafer ID',
    COL_ID: 'WAFERID',
    USE_YN: 'N',
    LIST_NUM: '24',
    key: '24',
  },
  {
    COL_TEXT: 'Remark',
    COL_ID: 'REMARK',
    USE_YN: 'N',
    LIST_NUM: '25',
    key: '25',
  },
];

export default defineData;
